version: '3.2'
services:
  web:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./:/app/
      - ./provisioning/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      
  php:
    image: php:7.2-fpm
    volumes:
        - ./:/app/